name: Docker

on:
  release:
    types: [published]
  push:
    branches:
      - "main"
jobs:
  build_image:
    name: Build Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Login in DockerHub registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_TOKEN }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: peregud/docker
